production:
    username: cdkbot
    uuid: cdkbot
    apikey: $SQA_API_KEY
    token: $SQA_API_KEY
    env_name: production
    weebl_url: https://solutions.qa.canonical.com
    jenkins_url: https://solutions.qa.canonical.com
    smtp_from: noreply@canonical.com
    smtp_pass: figandleaves
    smtp_port: 465
    smtp_server: smtp.canonical.com
    smtp_user: canonical
