name: Confirm Snap Builds

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Run on which branch

permissions:
  contents: read

jobs:
  release-track:
    runs-on: ubuntu-latest
    env:
      CHARMCRAFT_AUTH : ${{ secrets.CHARMCRAFT_AUTH }}
      LPCREDS_B64: ${{ secrets.LP_CREDS }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r scripts/requirements.txt
      - name: Install tools
        run: |
          sudo snap install snapcraft --classic
      - run: 'echo $LPCREDS_B64 | base64 --decode > lp_creds'
        shell: bash
      - name: Ensure Tracks and Recipes
        run: |
          LPCREDS=./lp_creds scripts/ensure_snap_builds.py --branch ${{ inputs.branch }}
