name: Confirm Snap Builds

on:
  workflow_dispatch:
    inputs:
      branches:
        type: string
        required: false
        default: ""  # defaults to all matching branches (main and release branches)
        description: Run on which k8s-snap branches (space separated). If empty, it will run on all matching branches (main and release branches).
  workflow_call:
    inputs:
      branches:
        type: string
        required: false
        default: ""  # defaults to all matching branches (main and release branches)
        description: Run on which k8s-snap branches (space separated). If empty, it will run on all matching branches (main and release branches).

permissions:
  contents: read

jobs:
  release-track:
    runs-on: ubuntu-latest
    env:
      CHARMCRAFT_AUTH : ${{ secrets.CHARMCRAFT_AUTH }}
      LPCREDS_B64: ${{ secrets.LP_CREDS }}
      LPCREDS: ./lp_creds
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - run: uv tool install tox --with tox-uv
      - name: Install tools
        run: |
          sudo snap install snapcraft --classic
      - run: 'echo $LPCREDS_B64 | base64 --decode > $LPCREDS'
        shell: bash
      - name: Ensure Tracks and Recipes
        run: |
          tox -e runner -- scripts/ensure_snap_builds.py --branch ${{ inputs.branches }}
