name: Build and Publish A Kubernetes Component Debian Package

on:
  pull_request:
    paths:
      - .github/workflows/publish-k8s-debs.yaml
  workflow_dispatch:
    inputs:
      component:
        description: "Kubernetes component to package"
        required: true
        type: choice
        options:
          - kubeadm
          - kubelet
          - kubectl
        default: kubeadm
      tag:
        description: "Upstream Kubernetes release tag (e.g., v1.32.3)"
        required: true
        type: string
        default: v1.32.3
      version-postfix:
        description: "Version postfix for the package (e.g., build1). Final deb version: {tag}-{version-postfix}"
        required: true
        type: string
        default: build1
      dry-run:
        description: "Dry run mode (true/false). If true, no upload to PPA will be performed."
        required: true
        type: boolean
        default: true
      log-level:
        description: "Log level for the script (e.g., DEBUG, INFO, WARNING, ERROR)."
        required: true
        type: string
        default: DEBUG

permissions:
  contents: read

jobs:
  publish-deb:
    name: Build and Publish Debian Package
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r scripts/requirements.txt
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y devscripts debhelper dh-make build-essential
      - name: Build and publish
        env:
          BOT_GPG_KEY: "${{ secrets.BOT_GPG_KEY }}"
          BOT_FULL_NAME: "${{ secrets.BOT_FULL_NAME }}"
          BOT_EMAIL: "${{ secrets.BOT_EMAIL }}"
          BOT_LP_ACCOUNT: "${{ secrets.BOT_LP_ACCOUNT }}"
        run: |
          ./scripts/publish_k8s_debs.py \
            "${{ inputs.component }}" \
            ${{ inputs.dry-run && '--dry-run' || '' }} \
            --tag "${{ inputs.tag }}" \
            --version-postfix "${{ inputs.version-postfix }}" \
            --log "${{ inputs.log-level }}"
