name: Build and Publish A Kubernetes Component Debian Package

on:
  workflow_dispatch:
    inputs:
      component:
        description: "Kubernetes component to package"
        required: true
        type: choice
        options:
          - kubeadm
          - kubelet
          - kubectl
        default: kubeadm
      tag:
        description: "Upstream Kubernetes release tag (e.g., v1.32.3)"
        required: true
        type: string
        default: v1.32.3
      version-postfix:
        description: "Version postfix for the package (e.g., build1). Final deb version: {tag}-{version-postfix}"
        required: true
        type: string
        default: build1
      dry-run:
        description: "Dry run mode (true/false). If true, no upload to PPA will be performed."
        required: true
        type: boolean
        default: true
      log-level:
        description: "Log level for the script (e.g., DEBUG, INFO, WARNING, ERROR)."
        required: true
        type: string
        default: DEBUG
      stable-ppa:
        description: "Upload to stable PPA (true/false). If true, the package will be uploaded to the stable PPA."
        required: true
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  publish-deb:
    name: Build and Publish Debian Package
    runs-on: ubuntu-24.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r scripts/requirements.txt
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y devscripts debhelper dh-make build-essential gnupg dput lintian
      - name: Import GPG key
        run: |
          echo "${{ secrets.DEBS_GPG_KEY_PUBLIC_BACKUP }}" > gpg_public.key
          echo "${{ secrets.DEBS_GPG_KEY_PRIVATE_BACKUP }}" > gpg_private.key
          gpg --import gpg_public.key
          gpg --import gpg_private.key
      - name: Build and publish
        env:
          DEBS_GPG_KEY: "${{ secrets.DEBS_GPG_KEY }}"
          DEBS_FULL_NAME: "${{ secrets.DEBS_FULL_NAME }}"
          DEBS_EMAIL: "${{ secrets.DEBS_EMAIL }}"
          DEBS_LP_ACCOUNT: "${{ secrets.DEBS_LP_ACCOUNT }}"
        run: |
          ./scripts/publish_k8s_debs.py \
          --tag "${{ inputs.tag }}" \
          --version-postfix "${{ inputs.version-postfix }}" \
          ${{ inputs.dry-run && '--dry-run' || '' }} \
          ${{ inputs.stable-ppa && '--stable-ppa' || '' }} \
          -l "${{ inputs.log-level }}" \
          "${{ inputs.component }}"
