name: Auto-update pre-release branches

on:
  pull_request:
    paths:
      - .github/workflows/update-pre-release-branches.yaml
  schedule:
    # Run 20 minutes after midnight, giving the k8s-snap nightly job
    # enough time to pick up new k8s releases and setup the git branches.
    - cron: "20 0 * * *"

permissions:
  contents: read

jobs:
  determine:
    name: "Determine k8s pre-releases"
    runs-on: ubuntu-latest
    outputs:
      gitBranches: ${{ steps.determine.outputs.gitBranches }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.BOT_SSH_KEY }}
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - run: uv tool install tox --with tox-uv
      - name: Determine outstanding pre-releases
        id: determine
        run: |
          gitBranches=`tox -qq -e runner -- ./scripts/k8s_release.py get_outstanding_prereleases --as-git-branch`
          echo "gitBranches=$gitBranches" >> "$GITHUB_OUTPUT"
  handle-pre-releases:
    name: Handle pre-releases
    needs: [determine]
    strategy:
      matrix:
          branch: ${{ fromJson(needs.determine.outputs.gitBranches) }}
    uses: ./.github/workflows/create-release-branch.yaml
    secrets: inherit
    with:
      branches: ${{ matrix.branch }}
