name: Upgrade Proposal Test

on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch of the k8s-snap to use for testing the proposal'
        required: true
        type: string
      dry_run:
        description: 'If true, it will trigger the test, but not promote on success'
        required: false
        type: boolean
      lxd-channel:
        description: 'The LXD channel to use for testing the proposal'
        default: '5.21/stable'
        type: string
      lxd-images:
        description: 'The LXD images to use for testing the proposal'
        required: true
        type: string
      proposal-name:
        description: 'The name of the proposal to test'
        required: true
        type: string
      revision:
        description: 'The snap revision to promote'
        required: true
        type: string
      runner-labels:
        description: 'The github runner-label for this job'
        required: true
        type: string
      snap-channel:
        description: 'The channels to promote the snap to'
        required: true
        type: string
      next-risk:
        description: 'The next risk level (beta, candidate, stable)'
        required: true
        type: string
      upgrade-channels:
        description: 'The upgrade paths to test'
        required: true
        type: string
    secrets:
      SNAPSTORE_AUTH_TOKEN:
        required: true
jobs:
  test-proposal-e2e:
    name: E2E tests on ${{ matrix.lxd-image}}
    runs-on: ${{ fromJson(inputs.runner-labels) }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        # a unique runner for each lxd-image
        lxd-image: ${{ fromJSON(inputs.lxd-images) }}
    env:
      TEST_INSPECTION_REPORTS_DIR: ${{ github.workspace }}/inspection-reports
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version-file: '.python-version'
      - name: Install uv
        uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff # v6
      - run: uv tool install tox --with tox-uv
      - name: Setup LXD
        uses: canonical/setup-lxd@a3c85fc6fb7fff43fcfeae87659e41a8f635b7dd # v0.1.3
        with:
          channel: ${{ inputs.lxd-channel }}
          bridges: "lxdbr0,dualstack-br0,ipv6-br0"
      - name: Download snap revision ${{ inputs.revision }}
        run: |
          snap download k8s --revision=${{ inputs.revision }} --basename k8s
      - name: Run e2e tests on ${{matrix.lxd-image}}
        env:
          TEST_SUBSTRATE: lxd
          TEST_SNAP: ${{ github.workspace }}/k8s.snap
          TEST_LXD_IMAGE: ${{ matrix.lxd-image }}
        run: |
          tox -e runner -- \
          scripts/promote_tracks.py \
            ${{ inputs.dry_run && ' --dry-run' || '' }} \
            test e2e \
            --branch="${{ inputs.branch }}" \
            --next-risk="${{ inputs.next-risk }}"
      - name: Upload inspection reports
        if: failure()
        uses: ./.github/actions/upload-inspection-reports
        with:
          artifact-name: e2e-test-${{ inputs.proposal-name }}-${{ matrix.lxd-image }}
          directory: ${{ env.TEST_INSPECTION_REPORTS_DIR }}
      - name: Debugging session
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: canonical/action-tmate@bda82e73586a62bf621881aab872a527c8a46e2d # main
        timeout-minutes: 10

  test-proposal-upgrade:
    name: ${{ join(matrix.upgrade-channels, ' to ')}} on ${{ matrix.lxd-image}}
    runs-on: ${{ fromJson(inputs.runner-labels) }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        # a unique runner for each lxd-image and upgrade-path
        lxd-image: ${{ fromJSON(inputs.lxd-images) }}
        upgrade-channels: ${{ fromJSON(inputs.upgrade-channels) }}
    env:
      TEST_INSPECTION_REPORTS_DIR: ${{ github.workspace }}/inspection-reports
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version-file: '.python-version'
      - name: Install uv
        uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff # v6
      - run: uv tool install tox --with tox-uv
      - name: Setup LXD
        uses: canonical/setup-lxd@a3c85fc6fb7fff43fcfeae87659e41a8f635b7dd # v0.1.3
        with:
          channel: ${{ inputs.lxd-channel }}
          bridges: "lxdbr0,dualstack-br0,ipv6-br0"
      - name: Run promotion tests from ${{ join(matrix.upgrade-channels, ' to ') }} on ${{matrix.lxd-image}}
        env:
          TEST_SUBSTRATE: lxd
          TEST_LXD_IMAGE: ${{ matrix.lxd-image }}
          TEST_VERSION_UPGRADE_CHANNELS: ${{ join(matrix.upgrade-channels, ' ') }}
          # Upgrading from 1.30 is not supported.
          TEST_VERSION_UPGRADE_MIN_RELEASE: "1.31"
          TEST_DEFAULT_WAIT_RETRIES: 200
          TEST_DEFAULT_WAIT_DELAY_S: 10
        run: |
          tox -e runner -- \
          scripts/promote_tracks.py \
            ${{ inputs.dry_run && ' --dry-run' || '' }} \
            test upgrade \
            --branch="${{ inputs.branch }}"
      - name: Upload inspection reports
        if: failure()
        uses: ./.github/actions/upload-inspection-reports
        with:
          artifact-name: promotion-test-${{ inputs.proposal-name }}-${{ join(matrix.upgrade-channels, ',')}}-${{ matrix.lxd-image }}
          directory: ${{ env.TEST_INSPECTION_REPORTS_DIR }}
      - name: Debugging session
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: canonical/action-tmate@bda82e73586a62bf621881aab872a527c8a46e2d # main
        timeout-minutes: 10
  promote-proposal:
    name: Promote ${{ inputs.revision }} to ${{ inputs.snap-channel }}
    runs-on: ${{ fromJson(inputs.runner-labels) }}
    needs: [test-proposal-upgrade, test-proposal-e2e]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version-file: '.python-version'
    - name: Install uv
      uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff # v6
    - run: uv tool install tox --with tox-uv
    - run: sudo snap install snapcraft --classic
    - name: Promote
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_AUTH_TOKEN }}
      run: |
          tox -e runner -- \
          scripts/promote_tracks.py \
          ${{ inputs.dry_run && ' --dry-run' || '' }} \
          promote \
          --snap-revision="${{ inputs.revision }}" \
          --snap-channel="${{ inputs.snap-channel }}"
